"""Citation formatting — exact format per docs/DATA_CONTRACT.md:
  [{file_name} · {section} · {policy_version} ({effective_date})]
  ...answer ends with an "Эх сурвалж:" list of the cited sources.

Kept deterministic and outside the LLM's control: this is a compliance
surface (CONTRIBUTING.md rule 2 — "No answer ships without a citation"), so the
exact citation text is generated by code from the chunks actually retrieved,
never left to the model to reproduce correctly.
"""

import re

from app.config import settings
from app.retrieve.models import RetrievedChunk

_NO_DATE = "огноогүй"
_NO_SECTION = "—"

# Multi-level numbered sub-clause ("4.1.2.", "1.1.") — the chunker
# deliberately does NOT split on these (app/ingest/chunker.py's
# _HEADING_PATTERNS require single-level numbering only), so they survive
# as plain text inside chunk.content. Requires 2-4 dotted levels so this
# never matches the chunker's own single-level headings ("1. Гарчиг").
_CLAUSE = re.compile(r"(?:^|\s)(\d+(?:\.\d+){1,3})\.\s+(?=\S)", re.MULTILINE)
_WHITESPACE = re.compile(r"\s+")
# The extracted description becomes part of a "[a · b · c (d)]" citation
# line parsed downstream by app/eval/runner.py and
# ui/src/lib/parseCitations.js via a "·"/"[]"/"()"-delimited regex — strip
# characters that would corrupt that shape.
_UNSAFE = re.compile(r"[·\[\]()]")


def _truncate(text: str, max_chars: int) -> str:
    if len(text) <= max_chars:
        return text
    head = text[:max_chars].rsplit(" ", 1)[0]
    return (head or text[:max_chars]) + "…"


def _extract_clause(content: str, preferred: str | None = None) -> tuple[str, str] | None:
    """The inline clause number in `content` to cite, plus a short verbatim
    description. Code-generated, never left to the model — same reason the
    rest of the citation format is deterministic (see module docstring).

    `preferred`, when given, is the specific clause the model's answer says
    it drew from (see extract_used_context) — honored only if it actually
    appears as one of `content`'s own clause numbers, verified against the
    SAME regex used to find them, never taken on the model's word alone
    (DATA_CONTRACT.md: "never invent a clause number that isn't in the
    text"). Falls back to the first clause found — the pre-existing
    behavior — when `preferred` is None or not present in this chunk.
    """
    matches = list(_CLAUSE.finditer(content))
    if not matches:
        return None
    match = None
    if preferred is not None:
        match = next((m for m in matches if m.group(1) == preferred), None)
    if match is None:
        match = matches[0]
    number = match.group(1)
    description = _WHITESPACE.sub(" ", content[match.end() :]).strip()
    description = _UNSAFE.sub("", description)
    return number, _truncate(description, settings.clause_description_max_chars)


def format_context_block(chunk: RetrievedChunk) -> str:
    section = chunk.section or _NO_SECTION
    return f"[{chunk.file_name} · {section} · {chunk.policy_version}]\n{chunk.content}"


def format_citation(chunk: RetrievedChunk, preferred_clause: str | None = None) -> str:
    clause = _extract_clause(chunk.content, preferred_clause)
    if clause is not None:
        number, description = clause
        section = f"Заалт {number}: {description}" if description else f"Заалт {number}"
    else:
        section = chunk.section or _NO_SECTION
    date_str = chunk.effective_date.isoformat() if chunk.effective_date else _NO_DATE
    return f"[{chunk.file_name} · {section} · {chunk.policy_version} ({date_str})]"


def _chunk_pk(chunk: RetrievedChunk) -> tuple[str, str, int]:
    return (chunk.file_name, chunk.policy_version, chunk.chunk_index)


def format_citation_list(
    chunks: list[RetrievedChunk],
    preferred_clauses: dict[tuple[str, str, int], str] | None = None,
) -> str:
    seen: set[tuple[str, str | None, str, object]] = set()
    lines: list[str] = []
    for chunk in chunks:
        key = (chunk.file_name, chunk.section, chunk.policy_version, chunk.effective_date)
        if key in seen:
            continue
        seen.add(key)
        preferred = preferred_clauses.get(_chunk_pk(chunk)) if preferred_clauses else None
        lines.append(format_citation(chunk, preferred))
    return "Эх сурвалж:\n" + "\n".join(lines)


# The model is told (SYSTEM_PROMPT in app.answering) to number each context
# block "[1]", "[2]", ... and append one trailing marker LINE PER block it
# actually drew from — narrower than "everything that passed the score
# floor" (app.retrieve.retriever.select_cited_chunks), since a chunk can
# clear that floor without the model ending up using it. Each line can also
# name the SPECIFIC inline clause it used within that chunk, when the chunk
# spans several — "4.1 shown instead of 4.2" is exactly the case this
# narrows. One line per chunk, not a single comma-packed line: an earlier
# version tried "АШИГЛАСАН: 1:4.2,3" in one line and a small model reliably
# broke it — bracketing the index ("[1]:..."), semicolons between chunks,
# multiple comma-separated clauses after one colon ("1:4.2.1, 4.2.2, 4.3.1")
# — all of which a single-line parse cannot tell apart from real entry
# boundaries. Splitting into "one line per chunk" removes the ambiguity
# entirely: each line is independently trivial to parse or skip. Both index
# and clause are a SELECTION signal only (which candidate, which of its own
# clause numbers), never citation TEXT itself — _extract_clause still
# verifies the named clause actually exists in the chunk before honoring
# it, and the rendered citation string stays fully code-generated, per this
# module's docstring.
_USED_LINE_SHAPE = re.compile(r"^\s*АШИГЛАСАН\s+\[?\d+\]?\s*:\s*.*$")
_USED_LINE = re.compile(
    r"^\s*АШИГЛАСАН\s+\[?(?P<idx>\d+)\]?\s*:\s*(?P<clause>\d+(?:\.\d+)+)?\s*$"
)


def is_used_marker_line(line: str) -> bool:
    """Whether `line` is shaped like an "АШИГЛАСАН N: ..." marker line —
    checked independently of whether it fully parses, so a malformed one
    (matches the shape but the clause doesn't) still gets treated as
    machine-only and never leaks to the employee verbatim. Exposed
    separately from extract_used_context for app.answering's streaming
    path, which must decide "hold this back" per line, before a full answer
    is available to parse."""
    return _USED_LINE_SHAPE.match(line.strip()) is not None


def extract_used_context(answer_text: str) -> tuple[str, list[tuple[int, str | None]] | None]:
    """Splits the trailing block of "АШИГЛАСАН N: [clause]" marker lines
    (one per used context block, contiguous at the very end — see
    SYSTEM_PROMPT rule 7) off `answer_text`, parsing each into a
    (chunk_index, clause) pair — clause is None when nothing follows the
    colon.

    Returns (answer_text_without_the_marker_lines, entries). `entries` is
    None when there are no marker lines at all — the caller's signal to
    fall back to citing everything that passed the score floor. An
    individual marker-shaped line whose clause doesn't parse is skipped,
    not treated as a parse failure for the whole block — fail open, same
    reasoning as query_expansion's failure handling: a parsing miss must
    never suppress a chunk that was genuinely used, only risk citing one
    extra that wasn't (or citing it under a less specific clause).
    """
    lines = answer_text.rstrip().splitlines()
    marker_start = len(lines)
    while marker_start > 0 and is_used_marker_line(lines[marker_start - 1]):
        marker_start -= 1
    if marker_start == len(lines):
        return answer_text, None
    entries = []
    for line in lines[marker_start:]:
        match = _USED_LINE.match(line.strip())
        if match is not None:
            entries.append((int(match.group("idx")), match.group("clause")))
    remaining = "\n".join(lines[:marker_start]).rstrip()
    return remaining, entries or None
