"""Citation formatting — exact format per docs/DATA_CONTRACT.md:
  [{file_name} · {section} · {policy_version} ({effective_date})]

format_citation() renders that string — used for the audit trail's
human-readable `answer_audit.citations` column (app.audit) — while
citation_fields() builds the STRUCTURED shape the API actually hands the
client (choices[0].citations / the streaming "citations" SSE event), for
its own citation drawer UI rather than a string to re-parse.

Kept deterministic and outside the LLM's control either way: this is a
compliance surface (CONTRIBUTING.md rule 2 — "No answer ships without a
citation"), so the exact citation content is generated by code from the
chunks actually retrieved, never left to the model to reproduce correctly.
"""

import re
from pathlib import Path

from app.config import settings
from app.retrieve.models import RetrievedChunk

_NO_DATE = "огноогүй"
_NO_SECTION = "—"

# Multi-level numbered sub-clause ("4.1.2.", "1.1.") — the chunker
# deliberately does NOT split on these (app/ingest/chunker.py's
# _HEADING_PATTERNS require single-level numbering only), so they survive
# as plain text inside chunk.content. Requires 2-4 dotted levels so this
# never matches the chunker's own single-level headings ("1. Гарчиг").
_CLAUSE = re.compile(r"(?:^|\s)(\d+(?:\.\d+){1,3})\.\s+(?=\S)", re.MULTILINE)
_WHITESPACE = re.compile(r"\s+")
# The extracted description becomes part of a "[a · b · c (d)]" citation
# line parsed downstream by app/eval/runner.py and
# ui/src/lib/parseCitations.js via a "·"/"[]"/"()"-delimited regex — strip
# characters that would corrupt that shape.
_UNSAFE = re.compile(r"[·\[\]()]")


def _truncate(text: str, max_chars: int) -> str:
    if len(text) <= max_chars:
        return text
    head = text[:max_chars].rsplit(" ", 1)[0]
    return (head or text[:max_chars]) + "…"


def _find_clause_match(content: str, preferred: str | None = None) -> re.Match | None:
    """The regex match _extract_clause/citation_fields both cite — factored
    out so the two agree on exactly which occurrence that is, rather than
    each re-deriving the "preferred, else first" selection independently.

    `preferred`, when given, is the specific clause the model's answer says
    it drew from (see extract_used_context) — honored only if it actually
    appears as one of `content`'s own clause numbers, verified against the
    SAME regex used to find them, never taken on the model's word alone
    (DATA_CONTRACT.md: "never invent a clause number that isn't in the
    text"). Falls back to the first clause found — the pre-existing
    behavior — when `preferred` is None or not present in this chunk.
    """
    matches = list(_CLAUSE.finditer(content))
    if not matches:
        return None
    if preferred is not None:
        match = next((m for m in matches if m.group(1) == preferred), None)
        if match is not None:
            return match
    return matches[0]


def _extract_clause(content: str, preferred: str | None = None) -> tuple[str, str] | None:
    """The inline clause number in `content` to cite, plus a short verbatim
    description. Code-generated, never left to the model — same reason the
    rest of the citation format is deterministic (see module docstring)."""
    match = _find_clause_match(content, preferred)
    if match is None:
        return None
    number = match.group(1)
    description = _WHITESPACE.sub(" ", content[match.end() :]).strip()
    description = _UNSAFE.sub("", description)
    return number, _truncate(description, settings.clause_description_max_chars)


_DOC_PREFIX = re.compile(r"^L\d-[A-Z]+-\d+_")


def _derive_title(file_name: str) -> str:
    """Human-readable title derived from `file_name` alone — deliberately
    not a join to policy_documents.title_mn, so this works uniformly for
    registry AND legacy files (DATA_CONTRACT.md's "Registry membership": a
    file with no Бүртгэлийн дугаар gets no policy_documents row at all, so
    relying on that table would leave some citations with no title)."""
    stem = _DOC_PREFIX.sub("", Path(file_name).stem)
    return stem.replace("_", " ").strip() or file_name


def citation_fields(
    index: int, chunk: RetrievedChunk, preferred_clause: str | None = None
) -> dict:
    """The structured citation shape the API returns to the client
    (choices[0].citations, and the streaming "citations" SSE event) —
    {index, docId, chunkId, title, clause, snippet, charStart, charEnd}.
    `chunkId` is policy_chunks' own PK, stringified — the stable identifier
    app.feedback's `retrievedChunkIds` records, since a document title/clause
    isn't itself a safe grouping key (two different chunks can render the
    same fallback section title). Deliberately
    separate from format_citation() above: that one builds the exact
    rendered string still used for the audit trail's human-readable
    `answer_audit.citations` column; this hands the CLIENT the raw
    material — the verbatim chunk text plus a char range — to render
    its own citation drawer, rather than a pre-formatted string it would
    have to re-parse (see ui/src/components/CitationDrawer.jsx).

    `index` is the chunk's position in the ORIGINAL "[1]", "[2]", ...
    numbering shown to the model (SYSTEM_PROMPT) — preserved through
    app.answering._resolve_used_context's narrowing so the inline "[N]"
    markers the model places in its own prose still resolve to the right
    entry even when not every numbered block ended up cited.

    `charStart`/`charEnd` are None when the chunk has no inline clause to
    highlight (no match found) — the client shows the whole snippet with no
    highlighted range in that case, never a fabricated one. When a clause IS
    highlighted, the range runs from just after its own number/punctuation
    through to (not including) wherever the NEXT clause number in the chunk
    starts, or the end of the chunk if this is the last one — i.e. exactly
    the clause's own text, the same span _extract_clause's `description`
    is built from.
    """
    match = _find_clause_match(chunk.content, preferred_clause)
    if match is not None:
        clause_number = match.group(1)
        char_start = match.end()
        next_match = next(
            (m for m in _CLAUSE.finditer(chunk.content) if m.start() > match.start()), None
        )
        char_end = next_match.start() if next_match is not None else len(chunk.content)
    else:
        clause_number = None
        char_start = None
        char_end = None

    return {
        "index": index,
        "docId": chunk.file_name,
        "chunkId": f"{chunk.file_name}::{chunk.policy_version}::{chunk.chunk_index}",
        "title": _derive_title(chunk.file_name),
        "clause": clause_number,
        "snippet": chunk.content,
        "charStart": char_start,
        "charEnd": char_end,
    }


def format_context_block(chunk: RetrievedChunk) -> str:
    section = chunk.section or _NO_SECTION
    return f"[{chunk.file_name} · {section} · {chunk.policy_version}]\n{chunk.content}"


def format_citation(chunk: RetrievedChunk, preferred_clause: str | None = None) -> str:
    clause = _extract_clause(chunk.content, preferred_clause)
    if clause is not None:
        number, description = clause
        section = f"Заалт {number}: {description}" if description else f"Заалт {number}"
    else:
        section = chunk.section or _NO_SECTION
    date_str = chunk.effective_date.isoformat() if chunk.effective_date else _NO_DATE
    return f"[{chunk.file_name} · {section} · {chunk.policy_version} ({date_str})]"


# The model is told (SYSTEM_PROMPT in app.answering) to number each context
# block "[1]", "[2]", ... and append one trailing marker LINE PER block it
# actually drew from — narrower than "everything that passed the score
# floor" (app.retrieve.retriever.select_cited_chunks), since a chunk can
# clear that floor without the model ending up using it. Each line can also
# name the SPECIFIC inline clause it used within that chunk, when the chunk
# spans several — "4.1 shown instead of 4.2" is exactly the case this
# narrows. One line per chunk, not a single comma-packed line: an earlier
# version tried "АШИГЛАСАН: 1:4.2,3" in one line and a small model reliably
# broke it — bracketing the index ("[1]:..."), semicolons between chunks,
# multiple comma-separated clauses after one colon ("1:4.2.1, 4.2.2, 4.3.1")
# — all of which a single-line parse cannot tell apart from real entry
# boundaries. Splitting into "one line per chunk" removes the ambiguity
# entirely: each line is independently trivial to parse or skip. Both index
# and clause are a SELECTION signal only (which candidate, which of its own
# clause numbers), never citation TEXT itself — _extract_clause still
# verifies the named clause actually exists in the chunk before honoring
# it, and the rendered citation string stays fully code-generated, per this
# module's docstring.
_USED_LINE_SHAPE = re.compile(r"^\s*АШИГЛАСАН\s+\[?\d+\]?\s*:\s*.*$")
_USED_LINE = re.compile(
    r"^\s*АШИГЛАСАН\s+\[?(?P<idx>\d+)\]?\s*:\s*(?P<clause>\d+(?:\.\d+)+)?\s*$"
)


def is_used_marker_line(line: str) -> bool:
    """Whether `line` is shaped like an "АШИГЛАСАН N: ..." marker line —
    checked independently of whether it fully parses, so a malformed one
    (matches the shape but the clause doesn't) still gets treated as
    machine-only and never leaks to the employee verbatim. Exposed
    separately from extract_used_context for app.answering's streaming
    path, which must decide "hold this back" per line, before a full answer
    is available to parse."""
    return _USED_LINE_SHAPE.match(line.strip()) is not None


def extract_used_context(answer_text: str) -> tuple[str, list[tuple[int, str | None]] | None]:
    """Splits the trailing block of "АШИГЛАСАН N: [clause]" marker lines
    (one per used context block, contiguous at the very end — see
    SYSTEM_PROMPT rule 7) off `answer_text`, parsing each into a
    (chunk_index, clause) pair — clause is None when nothing follows the
    colon.

    Returns (answer_text_without_the_marker_lines, entries). `entries` is
    None when there are no marker lines at all — the caller's signal to
    fall back to citing everything that passed the score floor. An
    individual marker-shaped line whose clause doesn't parse is skipped,
    not treated as a parse failure for the whole block — fail open, same
    reasoning as query_expansion's failure handling: a parsing miss must
    never suppress a chunk that was genuinely used, only risk citing one
    extra that wasn't (or citing it under a less specific clause).
    """
    lines = answer_text.rstrip().splitlines()
    marker_start = len(lines)
    while marker_start > 0 and is_used_marker_line(lines[marker_start - 1]):
        marker_start -= 1
    if marker_start == len(lines):
        return answer_text, None
    entries = []
    for line in lines[marker_start:]:
        match = _USED_LINE.match(line.strip())
        if match is not None:
            entries.append((int(match.group("idx")), match.group("clause")))
    remaining = "\n".join(lines[:marker_start]).rstrip()
    return remaining, entries or None
